### ISSUE TITLE
Comparison with react-jsonschema-form

### ISSUE THREAD

**Issue by dreadheadsic** [vtex/react-hook-form-jsonschema#21]
How does this compare to react-jsonschema-form? Have you ever used it and decided to create your own library? I'm getting frustrated with react-jsonschema-form and looking for alternatives so i stumbled upon your repo. Looks promising but not sure if it's good enough to be used in production.

**Comment by steckhelena** [comment]
I am going to be honest with you, this project was created to be some kind of substitute to react-jsonschema-form, but it is currently in early development, nevertheless we are preparing to release an app in production using it this week. The goal was to have a lighter(react-jsonschema-form minified weights about 70kb, this one is around 10kb) and more easily customizable alternative.
